Add Python version check to Mycodo installer (#712)

diff --git a/install/install b/install/install
--- a/install/install
+++ b/install/install
@@ -12,12 +12,29 @@
 #  curl -L https://raw.githubusercontent.com/kizniche/Mycodo/master/install/install | bash
 #
 
+INSTALL_DIRECTORY=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd -P )
+
 if [ -d ~/Mycodo ]; then
   printf "\n## Error: Install aborted. Cause: The ~/Mycodo directory already exists. The install cannot continue because a previous Mycodo install was detected. Please either move or delete the ~/Mycodo directory and rerun this script to initiate the install or run ~/Mycodo/install/setup.sh.\n"
   exit 1
 fi
 
-sudo apt-get install -y jq whiptail
+sudo apt-get install -y jq whiptail python3
+
+printf "Checking Python version...\n"
+if hash python3 2>/dev/null; then
+  if ! python3 "${INSTALL_DIRECTORY}"/mycodo/scripts/upgrade_check.py --min_python_version "3.6"; then
+    printf "Incorrect Python version found. Mycodo requires Python >= 3.6.\n"
+    printf "If you're running Raspbian 9 (Stretch) with Python 3.5, you will need to install at least Raspbian 10 (Buster) with Python 3.7 to install the latest version of Mycodo.\n"
+    exit 1
+  else
+    printf "Python >= 3.6 found. Continuing with the install.\n"
+  fi
+else
+  printf "\npython3 was not found. Cannot proceed with upgrade without python3 (Python >= 3.6).\n"
+  exit 1
+fi
+
 cd ~
 curl -s https://api.github.com/repos/kizniche/Mycodo/releases/latest | \
 jq -r '.tarball_url' | wget -i - -O mycodo-latest.tar.gz
